import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/public/home/Navbar";
import { Footer } from "@/components/public/home/Footer";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Clinic App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const raw = await headers();
  const session = await auth.api.getSession({ headers: raw });
  const user = session?.user;

  return (
    <html lang="fa" dir="rtl">
      <body dir="rtl" className="flex flex-col min-h-screen ">
        <Navbar user={user} />
        <main className="flex-grow">
          <div className="max-w-[1280px] mx-auto  px-4 sm:px-6 ">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
