import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/public/home/Navbar";
import { Footer } from "@/components/public/home/Footer";

export const metadata: Metadata = {
  title: "Clinic App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body dir="rtl" className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
